### ISSUE TITLE
Error creating new output folder

### ISSUE THREAD

**Issue by GitHabbo** [Sefhriloff/CCT-Extractor#1]
![Knipsel](https://user-images.githubusercontent.com/106544864/171048079-dd34b3a6-f873-4866-8188-8e33c24cbadd.PNG)
When selecting a cct to extract, the code checks if you've got an output directory.
If there is no directory present, it will try to create one, but it throws an error on line 78 (`fxObj = new(xtra("FileXtra4"))`).

```
on newFolder(tPath)
  fxObj = new(xtra("FileXtra4"))
  if not fx_FolderExists(fxObj, tPath) then fx_FolderCreate(fxObj, tPath)
end
```

**Comment by Sefhriloff** [comment]
Try this steps:

1- Make sure your Director has 'FileXtra4.x32' in the Xtras folder.
Here is my Director path 'C:\Program Files (x86)\Macromedia\Director MX 2004\Configuration\Xtras'
![11](https://user-images.githubusercontent.com/41347100/173115311-1883667b-6a15-4159-bfa0-cc3a5d8a0e2b.PNG)

2-Check if your .dir uses the xtra.
Modify > Movie > Xtras...
![1](https://user-images.githubusercontent.com/41347100/173115724-beb07e8e-14d3-48cd-ad25-49177799e832.PNG)
![2](https://user-images.githubusercontent.com/41347100/173115762-7150ad09-4758-416d-9c73-23c2ea0211a9.PNG)

3- At the end make sure you have the xtras folder in your program path.
![33](https://user-images.githubusercontent.com/41347100/173116111-2be45040-242d-4ab4-ab4b-61cec5b42381.PNG)
![44](https://user-images.githubusercontent.com/41347100/173116205-31133d96-817e-4565-b9e6-6b0903098dfa.PNG)
